apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      {{ range .Values.mockserverpath }}
        - path: {{ .mockname }}
          pathType: Prefix
          backend:
            service:
              name: mockserver
              port: 
                number: {{ .mockport }}
              {{- end }}
        # - path: /banana
        #   pathType: Prefix
        #   backend:
        #     service:
        #       name: banana-service
        #       port: 
        #         number: 5678
