apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      {{ range .Values.mockserver }}
        - path: {{ printf "/%s" .mockname }}
          pathType: Prefix
          backend:
            service:
              name: {{ .mockname }}
              port: 
                number: {{ .mockport }}
              {{ end }}
